apiVersion: v1
kind: Secret
metadata:
  name: event-service-secret
  namespace: dev-ns
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://narang24:narang24@happen.7qsjqbk.mongodb.net/?appName=Happen
  JWT_SECRET: fedfdb60b297682172b74b465f386d92039f6bea56b51e4594727c8e8307bf3585eef7c6e8363b4f068c6823ed9ed3347f5d64631fbd70cff508ef884cd308e0
  JWT_VERIFY_SECRET: 52d7291c01f53f2380a24d5b076fdea7f34ea37951fd910ab89cf6645c024c9f90b12a7c8347b2c8d9ddde83b7fe1e5d21cd19bec6ef486ab689a11c40647048
  JWT_PASSWORD_SECRET: 469a60917be163e41de3d9c4f5dfeb6cd666b0a973360b1329034500fdbb9c2345856bd680ee74a7b55046e7b8951ef7ccb4e1a0a074ad5adecb1696b68f0790