apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: dev-ns
spec:
  type: {{.Values.service.type}}
  selector:
    app: event-service
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.containerPort}}