apiVersion: v1
kind: Service
metadata:
  name: status-service
  namespace: dev-ns
spec:
  type: {{.Values.service.type}}
  selector:
    app: status-service
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.containerPort}}