apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: dev-ns
  labels:
    app: auth-service
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      name: auth-pod
      labels:
        app: auth-service
    spec: 
      containers:
        - name: auth-container
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          ports:
            - containerPort: {{.Values.containerPort}}
          envFrom:
            - configMapRef:
                name: auth-service-config 
            - secretRef:
                name: auth-service-secret
