apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: dev-ns
data:
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka-statefulset-0.kafka-service.dev-ns.svc.cluster.local:9093,1@kafka-statefulset-1.kafka-service.dev-ns.svc.cluster.local:9093,2@kafka-statefulset-2.kafka-service.dev-ns.svc.cluster.local:9093"
  KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  CLUSTER_ID: abcdefghijklmnopqrstuv
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"